### ISSUE TITLE
SendFormatMessage(ToAll)

### ISSUE THREAD

**Issue by TheVektor** [kurta999/YSF#12]
native SendFormatMessage(playerid, color, const message[], {Float,_}:...);
native SendFormatMessageToAll(color, const message[], {Float,_}:...);

I think its very useful in this plugin, and comfortable with using RPC.

RakSamp-ból másoltam, szerintem ez az :d

void SendClientMessage(PLAYERID playerID, DWORD dwColor, char* szMessage, ...)
{
	va_list va;
	va_start(va, szMessage);
	char szBuffer[512] = { 0 };
	vsprintf(szBuffer, szMessage, va);
	va_end(va);

	RakNet::BitStream bsParams;
	DWORD dwStrLen = strlen(szBuffer);

	bsParams.Write(dwColor);
	bsParams.Write(dwStrLen);
	bsParams.Write(szBuffer, dwStrLen);
	pRakServer->RPC(&RPC_ClientMessage, &bsParams, HIGH_PRIORITY, RELIABLE,
		0, pRakServer->GetPlayerIDFromIndex(playerID), FALSE, FALSE, UNASSIGNED_NETWORK_ID, NULL);
}

**Comment by oscar-broman** [comment]
`vsprintf` is not the same as the Pawn version `format` - it would cause unexpected behavior. What's wrong with the existing Pawn versions?

**Comment by kurta999** [comment]
Maybe, but first I need to find format_amxstring.  So don't wait this function :D

Use y_va now.

**Comment by IstuntmanI** [comment]
This should be closed.
