### ISSUE TITLE
QueryFlood wrong check

### ISSUE THREAD

**Issue by samphunter** [kurta999/YSF#16]
```
bool CheckQueryFlood(unsigned int binaryAddress)
{
	static DWORD dwLastQueryTick = 0;
	static unsigned int lastBinAddr = 0;

	if (!dwLastQueryTick) {
		dwLastQueryTick = (DWORD)GetTickCount();
		lastBinAddr = binaryAddress;
		return 0;
	}
	if (lastBinAddr == binaryAddress) { // Probably should be !=
		return 0;
	}
	if ((GetTickCount() - dwLastQueryTick) < 25) {
		return 1;
	}
	dwLastQueryTick = GetTickCount();
	lastBinAddr = binaryAddress;
	return 0;
}
```

+ Also the ban checking in RCON Packets seems not to work. Client was able to flood me eaven when he was banned. I had to disable rcon console
+ And also, the flood somehow caused both stack and heap underflow.

**Comment by kurta999** [comment]
I'll compare this to how actually done in samp server.

And yes, there are some problems because once I need to disable rcon to avoid rcon flood crash.

**Comment by samphunter** [comment]
if (lastBinAddr == binaryAddress) {
Im pretty sure this should be
if (lastBinAddr != binaryAddress) {

However, I have no idea about the ban not working.

**Comment by kurta999** [comment]
I've reverse engineered how it's in samp server currently, this is the result

bool CheckQueryFlood(unsigned int binaryAddress)
{
	static DWORD dwLastQueryTick = 0;
	static unsigned int lastBinAddr = 0;

	if(!dwLastQueryTick)
	{
		dwLastQueryTick = static_cast<DWORD>(GetTickCount64());
		lastBinAddr = binaryAddress;
		return 0;
	}
	if(lastBinAddr != binaryAddress)
	{
		if((static_cast<DWORD>(GetTickCount64()) - dwLastQueryTick) < 25)
			return 1;

		dwLastQueryTick = static_cast<DWORD>(GetTickCount64());
		lastBinAddr = binaryAddress;
	}
	return 0;
}

Hope this will work.

**Comment by samphunter** [comment]
Weird, I don't understand, how it is supposed to work.

**Comment by kurta999** [comment]
Fixed already.
