### ISSUE TITLE
Vehicle misc sync

### ISSUE THREAD

**Issue by NegativeIQ** [kurta999/YSF#18]
Some vehicles have special so called "misc" component (If you ever edited any vehicle model like tow truck or plane you know what i mean). Or you can use GGMM tool to explore these.

Misc is mostly moved with 8 and 2 on keypad, packer has one, forklift, tow truck, tractor...All planes also have misc, im not sure if i remember it right but im pretty sure its rear wings for them (unless they dont have it at all but think they do). And interesting thing is that cargo bob has one too.

Now these "misc" things they are synced in samp, but i dont know how and in what way...I through it was same as with hydras thrusters but its not...(At least from simple tests with GetPlayerHydraReactorAngle).

Anyone willing to dig thru vehicle syncing and try to find these so we can detect positions of these things?

**Comment by kurta999** [comment]
I have NO idea lol, it's interesting.

Maybe with key sync?

**Comment by oscar-broman** [comment]
They are only synced with key sync, afaik. You can test this by raising the fork in the forklift and teleporting a player from far away to you - if he does not see the fork raised, then it's not synced.
