### ISSUE TITLE
Breaks NetStats_ConnectionStatus

### ISSUE THREAD

**Issue by JernejL** [kurta999/YSF#19]
NetStats_ConnectionStatus once ysf is loaded starts to return what looks like garbage. 
 
[debug] Run time error 4: "Array index out of bounds"
[debug]  Accessing element at negative index -1454227448
 
-1454227448 is result from NetStats_ConnectionStatus which should be only one of 0 - 10 positive values found here: http://wiki.sa-mp.com/wiki/Connectionstatus 
 
Which hook is responsible for this?

**Comment by kurta999** [comment]
Going to check it soon.. Currently I'm away from computer. Maybe try to remove this line: https://github.com/kurta999/YSF/blob/YSF_/src/Hooks.cpp#L873

**Comment by JernejL** [comment]
Removed that, i'm not sure if it fixed it since i've commented out half the plugin because removing "a few hooks" kinda excelated. My timers stopped working after a while when i started to use the plugin and that triggered a chain reaction (i removed a few more hooks that i suspected could be related and then suddendly gang zones stopped working, so i kept trimming it down to minimum on what i needed to keep just the getpacketid hook - i use the hook to override keys there and not have the plugin crash the server). 
 
Ofcourse a better way for me to do it would be in CHookRakServer::Send -> RebuildSyncData, but there is no code in there yet to support rebuilding ID_VEHICLE_SYNC..

**Comment by kurta999** [comment]
Going to fix this + going to remove logprintf hook from linux, because that is unstable when lot of calls happen. IDK why.

**Comment by JernejL** [comment]
Onplayerconnect -> amx error -> crashdetect wants to output a message, ysf hooked it and called OnServerMessage, but pawn was already in a public call, crashdetect takes the problem seriously and calls exception again, printf hook proceeds to repeat.. until crash.
