### ISSUE TITLE
Compile with Windows XP compatibility?

### ISSUE THREAD

**Issue by Crayder** [kurta999/YSF#21]
Currently both, the latest beta release and the latest release, do not support Windows XP.

**Comment by JohnyMac** [comment]
You seriously need to update mate.. I don't know how are you living with windows XP.
Its support is removed and programs needs to remove their support too to be able to use any new features.

**Comment by Crayder** [comment]
Some of us are poor, ya know? I'd rather wait until I can actually afford a decent computer. I have Windows 7. This computer even came with Windows 7. It's just not as reliable on these low specs. I occasionally boot into Windows 7 for things that I need that require Windows 7 or greater. I also have a Windows 8.1 laptop (which also has Windows 10 on it, just pointing out that it's higher than Win7), but I don't use it much because it's just a cheap thing I got from someone. I do all of my work between my desktop and my other laptop (it has WinXP too).

So, it's not just something I can snap my fingers and do. Many others are the same.

**Comment by JohnyMac** [comment]
oh.. Sorry for the hard feelings, I didn't mean it at all.. Sorry.
I thought you where using it because you loved it or some sort of that.. :P

Psst, Mind opening skype for a sec ?

**Comment by paulommu** [comment]
Do you have the Visual C++ Redistributable 2015 packages installed on your computer? Microsoft says it is compatible with Windows XP Service Pack 3. Make sure your Windows is updated to SP3 and install the redistributable packages from here (both x86 and x64 if you are running on 64 bits, or x86 only if 32 bits): https://www.microsoft.com/pt-br/download/details.aspx?id=48145

**Comment by Crayder** [comment]
Do you have the Visual C++ Redistributable 2015 packages installed on your computer?

Yes, I do. But even with those redistributables the programmer needs to enable XP compatibility stuff.

**Comment by kurta999** [comment]
Get vs2008 and recompile the plugin, then it will work for sure. Sorry but im not going to support an outdated OS which is more than 10 years old.

**Comment by Crayder** [comment]
Maximum which i can do is compile plugin with 14_xp toolset. R16 will Come out soon that will be compiled with this.

And that's all you need.

**Comment by kurta999** [comment]
http://www.solidfiles.com/d/acc091408e/

This was compiled with vs_14, R16 beta

**Comment by Crayder** [comment]
(I'll test it later)

**Comment by kurta999** [comment]
Does it work?

**Comment by Crayder** [comment]
Damn it, I actually completely forgot to test it. I won't be home til Sunday, I'll be sure to test it then. I literally just set a reminder on Google and on my iPad.

**Comment by kurta999** [comment]
Can you check it please? :D I want to close this issue.

**Comment by Crayder** [comment]
Lol, yes of course... Give me a few minutes...

**Comment by Crayder** [comment]
Results with old:

	 Loading plugin: YSF
	logprintf = 0x0048C8D0
	
	
	
	 ===============================
	
	        YSF - kurta999 version R15 loaded
	
	   (c) 2008 Alex "Y_Less" Cole - (c) 2010 - 2015 kurta999
	
	    Server version: 0.3.7 R2-1
	
	    Operating System: Windows
	
	    Built on: Jan 21 2016 at 15:45:28
	
	 ===============================
	
	  Loaded.
	 Loaded 3 plugins.
	
	
	Filterscripts
	---------------
	  Loading filterscript 'console.amx'...
	native: SetWeather, SetWeather
	native: SetPlayerWeather, SetPlayerWeather
	native: SetPlayerWorldBounds, SetPlayerWorldBounds
	native: GetWeaponName, GetWeaponName
	native: SetGravity, SetGravity
	native: GetGravity, GetGravity
	native: GangZoneCreate, GangZoneCreate
	native: GangZoneDestroy, GangZoneDestroy
	native: GangZoneShowForPlayer, GangZoneShowForPlayer
	native: GangZoneShowForAll, GangZoneShowForAll
	native: GangZoneHideForPlayer, GangZoneHideForPlayer
	native: GangZoneHideForAll, GangZoneHideForAll
	native: GangZoneFlashForPlayer, GangZoneFlashForPlayer
	native: GangZoneFlashForAll, GangZoneFlashForAll
	native: GangZoneStopFlashForPlayer, GangZoneStopFlashForPlayer
	native: GangZoneStopFlashForAll, GangZoneStopFlashForAll
	native: SetPlayerTeam, SetPlayerTeam
	native: SetPlayerName, SetPlayerName
	native: SetPlayerSkin, SetPlayerSkin
	native: TogglePlayerControllable, TogglePlayerControllable
	native: SetPlayerFightingStyle, SetPlayerFightingStyle
	native: DestroyVehicle, DestroyVehicle
	native: ChangeVehicleColor, ChangeVehicleColor
	native: DestroyObject, DestroyObject
	native: DestroyPlayerObject, DestroyPlayerObject
	native: AttachObjectToPlayer, AttachObjectToPlayer
	native: AttachPlayerObjectToPlayer, AttachPlayerObjectToPlayer
	  Loading filterscript 'camctrl..amx'...
	  Unable to load filterscript 'camctrl..amx'.
	  Loaded 1 filterscripts.
	
	[debug] Run time error 19: "File or function is not found"
	[debug]  YSF_AddPlayer
	[debug]  YSF_RemovePlayer
	[debug]  YSF_StreamIn
	[debug]  YSF_StreamOut
	Script[gamemodes/bytes.amx]: Run time error 19: "File or function is not found"
	Number of vehicle models: 0
	--- Server Shutting Down.
	[debug] Run time error 19: "File or function is not found"
	[debug]  YSF_AddPlayer
	[debug]  YSF_RemovePlayer
	[debug]  YSF_StreamIn
	[debug]  YSF_StreamOut
	[debug] Server crashed due to an unknown error
	[debug] Native backtrace:
	[debug] #0 7c91168b in ?? () from C:\WINDOWS\system32\ntdll.dll
	[debug] #1 7c91084c in ?? () from C:\WINDOWS\system32\ntdll.dll
	[debug] #2 00fc821b in ?? () from C:\WINDOWS\system32\ucrtbase.dll
	[debug] #3 00e9c33f in ?? () from plugins\YSF.dll

Results with new... and an error dialog:

	 Loading plugin: YSF
	  Failed.

**Comment by kurta999** [comment]
Try latest r16 from download, that's also compiled with 14_xp toolset. That must work..

**Comment by Crayder** [comment]
You mean from the link you posted? That's the one I called 'new' in the results above.

**Comment by kurta999** [comment]
No,  go to releases page on git, get the latest and try it. If that wont work i have no idea...
