### ISSUE TITLE
Armor and health pulsing in car.

### ISSUE THREAD

**Issue by WeirdestYeti** [kurta999/YSF#24]
For some people this is happening and didn`t see pattern for when it`s happening.
Armor and health is pulsing like with s0beit hack, but its not the hack. Because if someone else enters same car after that person, its happening for him too.
And car health was increasing too. It was a big number  and kept growing.
http://i.imgur.com/XSqHqbs.jpg

**Comment by kurta999** [comment]
Going to check it, it's very interesting.

**Comment by JernejL** [comment]
This is a well known issue with how sa-mp sync works. 
 
When a player is in vehicle as driver, the player sends full data for player and vehicle health in the packets, this is then replicated to other clients based on vehicleid. 
 
If a car has 2 drivers, this will also replicate to other driver, making server covertly set his health, it also applies to armour. 
 
The only solution to this is a system that blocks updates of any other driver if the car suddendly has 2 drivers, one player has to be chosen as driver and other's updates blocked until other player is removed (plus a system to attempt to remove and if unsuccesful, disconnect the other driver). 
 
I have a system for this on partyserver based on player statuses (animations, vehicle request timings, pause time, etc..) that decides which player is the ONLY driver and block the rest.

**Comment by Tumba** [comment]
How to fix that? Have the same problem
