### ISSUE TITLE
RebuildRPCData not working on Linux

### ISSUE THREAD

**Issue by spmn** [kurta999/YSF#26]
It seems that RPC ID is wrong in RebuildRPCData. Result of printing ```uniqueID``` value at [this](https://github.com/kurta999/YSF/blob/d853813b944277d4c65dfceb3eb0a3338387633c/src/CPlayerData.cpp#L526) line:

```
[22:08:14] RPC: 11141180
[22:08:14] RPC: 1866924105
[22:08:14] RPC: 1931804765
[22:08:14] RPC: 6160523
```

On Windows everything is fine.

**Comment by kurta999** [comment]
https://github.com/kurta999/YSF/commit/56ba9b51d42beebb3d00fed53b1bd0396bd0c0ad
