### ISSUE TITLE
Compile without redistributable microsoft stuff

### ISSUE THREAD

**Issue by Peter-Harmann** [kurta999/YSF#27]
Can you change your compile options to compile without the redistributables like MSVCP140.dll?

http://ctrlv.in/723016

**Comment by Crayder** [comment]
All you need to do is install the vs2015 redistributables.

All that option does is include the required libraries in the DLL. This isn't always the best option. It also makes a much larger file... xD

**Comment by Peter-Harmann** [comment]
I get that, but lot of beginners don't :D But I guess it is the authors choice. I just prefer to ship everything in one file to avoid confusion. It is not like the size is too important these days.

**Comment by Crayder** [comment]
Those "lot of beginners" that don't know they need to install software to support basically ALL the software there is shouldn't have a computer at all, and you expect them to run a SA-MP server? Ha! Even SA-MP (both client and server) requires redistributables.

**Comment by Peter-Harmann** [comment]
I don't even know what to reply to you. Sure, everyone who is not as smart as you should just throw their PC out of a window...

I just got two questions about what the missing dll error means in a very short period of time, so I wrote this. If kurta999 does not want to include the redistributables, fine. I just made a suggestion to consider.

**Comment by kurta999** [comment]
I'm not going to do this, it's in the main post that you need visual c++ redistributable 2015 to load the plugin. 

Plus this "program" is a very basic, almost everything need it.

**Comment by Peter-Harmann** [comment]
OK, I understand.
