### ISSUE TITLE
no print message with percentage

### ISSUE THREAD

**Issue by aeifr** [kurta999/YSF#30]
Version: R16

The plugin affects strings which are going to be printed.
It's not required to include the include file
This also affects format() and on top of this BlueG's mysql plugin.

`   print("%Y %D %M");
    print("%h:%i:%s %x");

```
print("Y D M");
print("h i s x");

print("%Y ");
print("%D ");
print("%M");

print("%h");
print("%i ");
print("%s");
print("%x");
```

`

Result
`
Y D M
h i s x
`

**Comment by kurta999** [comment]
This doesnt affect format only print function. Maybe i will try to fix it.

**Comment by kurta999** [comment]
https://github.com/kurta999/YSF/commit/40f0c31318230f64267622f223a6f60dbaffb052
