### ISSUE TITLE
SendBulletData on linux

### ISSUE THREAD

**Issue by JernejL** [kurta999/YSF#32]
SendBulletData does not function on linux, regardless of whatever i try, it works on windows only.

windows:
YSF - pNetGame: 0x2E9F08, pRakServer: 0x2EE410 

linux:
YSF - pNetGame: 0x8306BD0, pRakServer: 0x830A8E0

**Comment by oscar-broman** [comment]
You probably want to have a look at this repo: https://github.com/IllidanS4/YSF

Apparently kurta is in jail for 10 years.

**Comment by kurta999** [comment]
Everything will be fixed soon. (after 2-3 weeks)

**Comment by Crayder** [comment]
KURTA RETURNS!

**Comment by kurta999** [comment]
https://github.com/kurta999/YSF/commit/c9126b4bbb240eab5645b8121af9060b4e991bcd

It should be fixed.
