### ISSUE TITLE
License

### ISSUE THREAD

**Issue by samphunter** [kurta999/YSF#36]
Hi, I would like to use some of your code (adresses and structures in server and related functions) in my plugin, but there is no license here. Would you mind me using it? And could you write a license or use some generic one?

**Comment by Crayder** [comment]
Technically speaking, no license = no license. Which in turn means yes, you can use the code, as has many other plugin developers.

**Comment by Whitetigerswt** [comment]
That's not exactly how no license works, see here: http://choosealicense.com/no-license/

**Comment by Crayder** [comment]
This is YSF we're talking about. It's a fork itself.

**Comment by kurta999** [comment]
YSF is under MPL 1.1, check the header of any source file and you will see.
