### ISSUE TITLE
GetVehicleNumberPlate

### ISSUE THREAD

**Issue by Xerieos** [kurta999/YSF#38]
GetVehicleNumberPlate(vehicleid, plate[], len = sizeof(plate));

This func writes an emtpy string into plate[], if SetVehicleNumberPlate() isn't called ever before.
I suggest set default number "XYZSR998" for every vehicle at creating.

**Comment by kurta999** [comment]
Thx.

**Comment by kurta999** [comment]
XYZSR998 is the default? Really?

**Comment by Konstantinos-Sk** [comment]
Yes, this is the default number plate.

**Comment by kurta999** [comment]
https://github.com/kurta999/YSF/commit/d6817d7fa26964be585577b24598511f26b94ed5
