### ISSUE TITLE
OnPlayerSend/ReceivePacket / OnPlayerSend/ReceiveRPC

### ISSUE THREAD

**Issue by IstuntmanI** [kurta999/YSF#39]
Originally created here: https://github.com/IllidanS4/YSF/issues/7

--------------

I made this suggestion on forums too (a little bit different): http://forum.sa-mp.com/showpost.php?p=3736888&postcount=73 . I think it's more organised if it is here. A callback is even better, without having the plugin to store the last X packets/RPCs.

Those callbacks should have the parameters _( playerid, rpcid/packetid, details[ ] )_ . Anyway, I still don't know how the _details_ string should look.

EDIT: It could even be something like

``` pawn
forward OnPlayerDataTransfer( playerid, type, id, direction, details[ ] );
// type: 0 - Packet, 1 - RPC
// id: the ID of the Packet/RPC
// direction: 0 - Sent, 1 - Received
// details: I don't know, what data is sent/received, I don't know if it should be an array instead, but you need all Packets and RPCs informations

**Comment by kurta999** [comment]
What do you think about this plugin?

https://github.com/urShadow/RakNetManager

**Comment by IstuntmanI** [comment]
Wow, awesome ! It sounds familiar, I don't know how I missed it. I probably forgot about it.

It could be useful for YSF too, if you want to implement a similar thing.

**Comment by kurta999** [comment]
I don't want to implement it since it's another project and looks like these works together.

It's not a miracle that you didn't saw this, it's isn't on SAMP forums and never will be.

**Comment by IstuntmanI** [comment]
Not directly implementing it, but maybe you have additional and different ideas for it. For now, it looks alright for me (even thought I have few questions about it, but I guess I'll discover the answers if I work with it).

Well, I do remember stalking urShadow's repositories (because he has some really cool things there), I remember that I saw this plugin some time ago, but I forgot about it.

**Comment by kurta999** [comment]
I think I'm gonna close this issue. I haven't arranged to implement something like this feature because it requires lot of time wihch I don't have now.
