### ISSUE TITLE
Would it help?

### ISSUE THREAD

**Issue by Sasuke-Uchiha** [kurta999/YSF#42]
If i don't wanna use some functions of YSF like it's interference with DIALOGS and other things I just want that HidePlayerForPlayer and ShowPlayerForPlayer Functions, Gravity Functions. So commenting other functions would help?

**Comment by kurta999** [comment]
It depends on what are you comment.

**Comment by Sasuke-Uchiha** [comment]
I tried commenting other things but it would still interfere.
