### ISSUE TITLE
IsPlayerPaused returns wrong result

### ISSUE THREAD

**Issue by Bios-Marcel** [kurta999/YSF#43]
Sometimes returns true, even tho the player is not paused at all.

What did i do when it occured? I removed his vehicle, removed all streamed objects(icognito Streamer), loaded new objects and tried to spawn him with "IsPlayerPaused"as condition. At that point and time he was: Spawned, Onfoot, not paused

**Comment by karimcambridge** [comment]
Just remember, lag can cause that!

**Comment by Bios-Marcel** [comment]
It always happens at the point

**Comment by Crayder** [comment]
>or should i jsut use GetPlayerPausedTime and find a good value myself?

This! IsPlayerPaused tells us if the player isn't updating for some pre-chosen time, GetPlayerPausedTime tells us how long ago the player was updating.

**Comment by spmn** [comment]
@Crayder Those functions are registered as natives, too.

**Comment by kurta999** [comment]
These natives already in inc too loo

**Comment by Crayder** [comment]
Huh, I never noticed them... damn... xD
