### ISSUE TITLE
GetVehicleNumberPlate

### ISSUE THREAD

**Issue by Xerieos** [kurta999/YSF#45]
i get number plate like this:

`new plate[16]`
`GetGehicleNumberPlate(vehicleid, plate);`

but it shows me incorrect hieroglyphs
![bandicam 2017-01-02 16-49-13-264](https://cloud.githubusercontent.com/assets/18464685/21587909/79913f82-d10b-11e6-9e80-b37337e85449.jpg)

**Comment by Crayder** [comment]
Two things:
- IIRC you need to use SetVehicleNumberPlate for GetVehicleNumberPlate to work.
- That string looks like you might've did something like this (which fails in all C languages except C#):

>new firstString[16], otherString[128] = "some random stuff that doesn't fit it 'firstString'";

For some reason that puts a bunch of crap in `firstString`.

**Comment by kurta999** [comment]
Now i dont have pc so i cant test iz because im moving. Try the output with ysf examples, im curious what it will be.

Getting works without setting, it will return the default plate.

**Comment by Crayder** [comment]
> Getting works without setting, it will return the default plate.

Oh yeah! Now I remember you fixing that, in #38.

**Comment by kurta999** [comment]
Fixed
