### ISSUE TITLE
Attached Camera not working well since R18.

### ISSUE THREAD

**Issue by rt-2** [kurta999/YSF#49]
Hello,
On my server I have a complex First Person system.
I use `AttachDynamicObjectToPlayer` and `AttachCameraToDynamicObject` and it worked 100% of the time.
But then I updated to R18 or R18-2 and the same script doesn't work, the updates to the camera are made 1/16 of the times instead of all the times.
Changes to the camera is triggered for example when crouching.
I have put some `printf` to diagnose, at first I tought it was a problem with `OnPlayerKeyStateChange`, but no, it works untill the `AttachDynamicObjectToPlayer` and the function even returns 1, but the camera is not moved.
Normally `AttachDynamicObjectToPlayer` is called once, then `AttachCameraToDynamicObject` just changes the camera position, but I also tried with both all the time and even a `SetDynamicObjectPos` to the player's position before and nothing works.

I guess it has something to do with how the camera attaches to dynamic objects....
I need help to find how to correct this, maybe there is a new way to do it. I sure hope it wont need a new update or this...
When I revert to R16 it just works as is...

Thank you,
rt-2

**Comment by kurta999** [comment]
There is a delay added to attached objects due to crashes, looks like i have to remove it when you attach it to yourself.  It will be fixed soon

**Comment by kurta999** [comment]
Tempomary solution would be using timer to attach camera after attaching object, eg after 2 second.

**Comment by rt-2** [comment]
I don't know why but using non-dynamic objects doesn't allow for a smooth camera movement.

**Comment by rt-2** [comment]
That's fixed too, since R19

**Comment by kurta999** [comment]
Thats good but AttachPlayerObjectToPlayer currently a bit bugged, it will be fixeed too soon im final r19

**Comment by rt-2** [comment]
Ok thank you, I have seen that, it bugs for me about 1/16 of the time, but then it fixes itself with my script, but Yes you are right there is still some glitches that wasn't there before...
Thank you for the information, can't wait for the official R19...
Thank you for your work.
