### ISSUE TITLE
YSF crashes the server OnPlayerConnect if https://github.com/maddinat0r/samp-tsconnector is used

### ISSUE THREAD

**Issue by Bios-Marcel** [kurta999/YSF#52]
When I use YSF and TSConnector at the same time, YSF crashes the server as soon as a player connects to the SA-MP server (i didn't call anything from TSConnector)

Link to the issue at samp-tsconnector: https://github.com/maddinat0r/samp-tsconnector/issues/16

**Comment by kurta999** [comment]
Im going to test it

**Comment by Bios-Marcel** [comment]
Sure, thanks, if you need any additional information, tell me.

**Comment by kurta999** [comment]
Only at linux?
