### ISSUE TITLE
Long connection to the server

### ISSUE THREAD

**Issue by kenjutsu-sx** [kurta999/YSF#59]
When connecting to server hangs for 5 seconds at "Сonnected. Joining the game..." and then called OnPlayerRequestClass etc.
I created a new server and connected only YSF.so, still long connection.

YSF version: R18 (R19 same problem)
Server version: 0.3.7 R2-1

Sorry for my bad English (I am from Russia).

The log is clean...

**Comment by kurta999** [comment]
Interesting, for me everythings work ok. Did you load ysf as latest plugin? What plugins are you using?

**Comment by kenjutsu-sx** [comment]
I downloaded the latest server version from the official site and connected only YSF.

**Comment by kenjutsu-sx** [comment]
You do not have a time for my issue? :)

**Comment by kurta999** [comment]
Could you send me the complete server package in. rar which repeoduces this issue? I would like to test it with debugger.

**Comment by kenjutsu-sx** [comment]
http://rgho.st/86VWBm47w

**Comment by kurta999** [comment]
Thanks i will test it soon

**Comment by kenjutsu-sx** [comment]
Hi! Is there progress?

**Comment by kurta999** [comment]
I was unable to reproduce this issue, on my side everything works

**Comment by Jlalt** [comment]
Its problem depends on connection. Try running this server package on far distance host to gey atleast 250 ms ping or smth then you may try the result.

**Comment by kenjutsu-sx** [comment]
I checked on another computer, where ping about 100 is the same problem.

46.174.50.41:7822 - someone can look (you should have at least 150 ping, this is Moscow hosting)

**Comment by rt-2** [comment]
I have ping 160-170, and when I connect it it takes about 1-2 seconds after it says "Сonnected. Joining the game..." for me to see your intro screen.
I think this is totally normal.
rt-2

**Comment by kenjutsu-sx** [comment]
rt-2, i have 90-110 ping, and the connection takes about 6-7 seconds...

Good.
Why the local server is also a long connection (although kurta999 says otherwise)?

**Comment by rt-2** [comment]
The connection takes 6-7 seconds too, but the there is 4 second after "Connecting to ...", and then another 2 seconde after "Сonnected. Joining the game...".
The first 4 second doesn't count.
rt-2

**Comment by kurta999** [comment]
But this is a client freeze, not server. The server wont hant hang up until you are connected.  Here is not problem ysf

**Comment by kenjutsu-sx** [comment]
"Connecting to ..." - 1 second (with 90-110 ping)
"Сonnected. Joining the game...". - 6-7 second (minimum 6)

Obviously this is a YSF problem, because if disable it, the "Connected.Joining the game ..." screen takes a maximum 2 seconds

**Comment by rt-2** [comment]
Well when I tried to connect to the given server I had 170ms and it took that exact "maximum 2 seconds" on "Сonnected. Joining the game...".
Maybe there is something else than ping, maybe the PC's performance?

**Comment by kenjutsu-sx** [comment]
rt-2, I checked on a fairly weak computer and powerful enough. I don't think it's because of this
