### ISSUE TITLE
Making a catch-all DoXForPlayer

### ISSUE THREAD

**Issue by oscar-broman** [kurta999/YSF#6]
What about hooking the RakNet broadcast method? That way, it could be customized who the next packets get sent to.

This would give a lot of flexibility to Pawn scripters.

For example:

``` c++
// This would enable/disable the functionality
native SetExclusiveBroadcast(toggle);
// This would add a player to the list of who will receive the packet
native BroadCastToPlayer(playerid, toggle = true);

public OnPlayerConnect(playerid) {
    SetExclusiveBroadcast(true);
    BroadCastToPlayer(playerid);
    SetGravity(0.0);
    SetExclusiveBroadcast(false);

    return 1;
}
```

**Comment by JernejL** [comment]
I like this oscar's idea, it's not bad at all, it has some niche but very cool uses.

**Comment by kurta999** [comment]
Hm..

Just an idiot question :D
Now I know how to hook RakServer::RPC, it's very easy.

BroadCastToPlayer would add given players into a vector, and while SetExclusiveBroadcast is true, only that players would get RPC's whose in that vector.

I hope it would work.

**Comment by oscar-broman** [comment]
Is this possible now?

**Comment by kurta999** [comment]
I'll look after but now I think it's now closer to possible like it was before.
