### ISSUE TITLE
SetVehicleSpawnInfo

### ISSUE THREAD

**Issue by JernejL** [kurta999/YSF#9]
Is this possible to add a function to change existing vehicle's spawn info coordinates and have respawnvehicle spawn the vehicle at new place?

**Comment by kurta999** [comment]
Hm... Look's like yes.

**Comment by JernejL** [comment]
Alright, something like this - i need, will appreciate if it's added.

**Comment by kurta999** [comment]
Hm...

Looks like set vehicle to new position after SetVehicleToRespawn used is very easy, just need to hook SetVehicleToRespawn. But spawn at new spawn when server respawn the vehicle because respawntime passed, it's harder. (need to hook complete CVehicle::Respawn which I do now want to do)

**Comment by JernejL** [comment]
what about just re-sending the "create vehicle" rpc to override it with new spawn position data?

**Comment by kurta999** [comment]
That is what i want to do :d

**Comment by kurta999** [comment]
You cant override,  just create new vehicle

**Comment by JernejL** [comment]
could you create a new vehicle with SAME old id?
Delete old id create vehicle with same old id again on all clients?

**Comment by kurta999** [comment]
Yes, this is how i imagined the solution.

**Comment by JernejL** [comment]
So, is this feasible? if it did that it would be a winner, because it would keep the same vehicle id on which a lot of code relies.

**Comment by kurta999** [comment]
Don't worry, this will work. I just need to implement it. I'll do it when i'll have free time.

**Comment by JernejL** [comment]
It will be Awesome!

**Comment by oscar-broman** [comment]
I saw c0c6d6c8b0d7846366c8c7d2e28a6fa17cc6a831 but that seems like a lot of unnecessary work. You could just send the RPC to remove the vehicle then send the vehicle spawn RPC with the same vehicle ID and new position parameters.

That, combined with hooking the Pawn native functions for creating vehicles would become a complete solution.

**Comment by kurta999** [comment]
I want to do that, but I want completly hook CVehicle::Spawn, hook pawn native SetVehicleToRespawn isn't enough..

**Comment by NegativeIQ** [comment]
Why not just mess with vehicles pool? Just do everything like in GetVehicleSpawnInfo only set new info. Next time vehicle is bound to respawn it should access that memory and respawn it at new coordinates.

Also i have seen there is something implemented already, is it working or? (If it is why not close issue?)

**Comment by kurta999** [comment]
Maybe this will be in R16 :)

Currently works for stream in vehicles, need to figure out how to solve with unstreamed vehicles.
